Add check for nonexistent user of instance group
slntopp/nocloud-driver-ione pull request #35
Opened 2022-08-15 12:52 UTC by ijimiji

2022-08-15 13:33 UTC, thnxvlad requested changes

2022-08-15 13:33 UTC, thnxvlad commented on pkg/driver/user.go
> +func transferOwnership(c *ONeClient, inst *pb.Instance, newUserID int, oldUserID int, userGroup int) error {
good naming but it seems to me that "change" will look better than "transfer"

2022-08-15 13:33 UTC, thnxvlad commented on pkg/driver/user.go
> +	}
 Very strange things going on here, I would like to confuse it with you in dm

2022-08-16 11:32 UTC, slntopp requested changes
- these functions must be *ONeClient methods
- suggest moving network and vms related methods to `pkg/driver/vnet.go` and `pkg/driver/vm.go` accordingly

2022-08-17 11:20 UTC, slntopp approved these changes

2022-08-24 11:10 UTC, thnxvlad approved these changes

2022-08-24 16:02 UTC, merged